# Generated by Django 3.1.6 on 2021-02-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('resumen', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='img')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meriland.clasificacion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
