# Generated by Django 3.1.6 on 2021-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=500)),
                ('motivo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
    ]
