# Generated by Django 3.1.6 on 2021-02-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0003_comentarios_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referencia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
