# Generated by Django 3.1.6 on 2021-02-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meriland', '0006_auto_20210218_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='paramovil',
            field=models.BooleanField(default=False),
        ),
    ]
