# Generated by Django 3.1.6 on 2021-02-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0007_auto_20210218_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
