# Generated by Django 3.1.6 on 2021-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='esnoticia',
            field=models.BooleanField(default=True),
        ),
    ]
