# Generated by Django 3.1.6 on 2021-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0012_post_esnoticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.TextField(),
        ),
    ]
