# Generated by Django 3.1.6 on 2021-02-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0014_post_espromocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='recaptcha',
            field=models.BooleanField(default=True),
        ),
    ]
