# Generated by Django 3.1.6 on 2021-02-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0015_comentarios_recaptcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='recaptcha',
        ),
    ]
