# Generated by Django 3.1.6 on 2021-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0017_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
