# Generated by Django 3.0.5 on 2021-03-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meriland', '0018_auto_20210306_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nacimiento',
            field=models.DateField(blank=True, null=False),
        ),
    ]
