# Generated by Django 3.0.5 on 2021-03-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0020_auto_20210316_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaNueva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
