# Generated by Django 3.0.5 on 2021-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0021_auto_20210316_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablanueva',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
