# Generated by Django 3.0.5 on 2021-03-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0022_tablanueva_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablaNueva',
        ),
    ]
