# Generated by Django 3.0.5 on 2021-03-16 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meriland', '0024_auto_20210316_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='paramovil',
        ),
        migrations.AlterField(
            model_name='post',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='meriland.Clasificacion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='titulo',
            field=models.CharField(default='Sr(a)', max_length=50),
        ),
    ]
