# Generated by Django 3.0.5 on 2021-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0025_auto_20210316_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiencia',
            field=models.TextField(null=True),
        ),
    ]
