# Generated by Django 3.0.5 on 2021-03-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0027_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experiencia',
        ),
    ]
