# Generated by Django 3.0.5 on 2021-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0028_remove_profile_experiencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-nombre']},
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
