# Generated by Django 3.0.5 on 2021-03-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0029_auto_20210318_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
