# Generated by Django 3.0.5 on 2021-03-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0030_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
