# Generated by Django 3.0.5 on 2021-03-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meriland', '0032_perfil_post'),
    ]

    operations = [
    ]
